mcsmsxfm56/henry-project-flipper

flipper/package-lock.json
flipper/src/pages/api/users/register/index.ts
flipper/src/utils/funcFile.ts

-Se instancio Prisma
-Se conecto con supabase
-Register endpoint y funcionalidad terminada
-GetEmpresas para traer todas las empresas

se instancio prisma y conexion con supabase

---

flipper/package-lock.json
flipper/package.json
flipper/prisma/schema.prisma
flipper/src/pages/api/users/login/index.ts

arreglo bug prisma eschema

---

flipper/src/components/CompanyRegisterForm.tsx
flipper/src/components/InputField.tsx
flipper/src/components/LoadingSubmitForm.tsx
flipper/src/components/RegisterForm.tsx
flipper/src/components/RegisterFormOLD.tsx
flipper/src/components/SelectField.tsx
flipper/src/components/WorkerRegisterForm.tsx
flipper/src/pages/app/register/index.tsx
flipper/src/services/PostRegister.ts
flipper/src/types/Types.ts

El formulario de registro está medio completo:
- El registro de empresa funciona
- Falta el registro de trabajador
- Los estilos están incompletos, pero trato de asemejarlos a la demo de flipper

24 hacer front register formulario merge into develop

---

flipper/src/pages/api/empresa/index.ts
flipper/src/pages/api/event/index.ts
flipper/src/pages/api/trabajador/index.ts

de paso ya que estaba deje la estructura de las rutas armadas, falta codearlas nomas, segui el modelo CRUD para hacerlas (asi ya tenemos una API para manejar todas las tablas de la BD)

39 ruta post apievent para crear eventos

---

flipper/prisma/schema.prisma
flipper/src/pages/api/empresa/[nombre].ts
flipper/src/pages/api/empresa/index.ts

cuando mergee esto ejecuten npx prisma generate para que se les actualize el nuevo modelado en su local repositorie

ruta terminada y hotfix al modelado bd

---

flipper/prisma/schema.prisma
flipper/src/pages/api/event/[id].ts
flipper/src/pages/api/event/index.ts

aprobado el pull request npx prisma generate

hotfix bd y rutas terminadas

---

flipper/src/pages/api/users/login/index.ts

falta crear controladores para sacar la logica de la ruta
falta tipar los datos

login para trabajador y empresa listos

---

flipper/src/pages/api/trabajador/[id].ts
flipper/src/pages/api/users/register/trabajador.ts

Se agrego el endpoint para poder actualizar la informacion del trabajador.
Este mismo toma como parametro en la url el id y necesita de la autorizacion del token, sin token no podra actualizar nada.
Se van a poder actualizar todos los campos, menos la contraseña, el tipo de documento, el numero del documento y el nombre de la persona.

44 ruta update apitrabajador

---

flipper/src/pages/api/trabajador/[id].ts
flipper/src/services/trabajadorController.ts

Se agrego la ruta delete para los trabajadores
Este mismo necesita del id para poder funcionar

ruta delete trabajador

---

flipper/src/hooks/useSesionUsuarioContext.ts
flipper/src/pages/index.tsx
flipper/src/services/iniciarSesion.ts
flipper/src/utils/validationSchema.ts

- Yup y Formik hacen las validaciones del login y tiran mensajes cuando los campos estan incompletos o si el email tiene un formato incorrecto

Task/validaciones en el login con Formik y Yup

---

flipper/src/components/EventCard.tsx
flipper/src/components/ListaDeEventos.tsx
flipper/src/pages/api/empresa/[nombre].ts
flipper/src/pages/empresa/index.tsx
flipper/src/pages/home/index.tsx

Se agrego componente para mostrar la lista de eventos activos de la empresa logueada

se agrego componente de lista de eventos

---

flipper/src/components/EventCard.tsx
flipper/src/components/Eventos.tsx
flipper/src/components/ListaDeEventos.tsx
flipper/src/pages/home/index.tsx

se mueve la lista a home y se centra

---

flipper/src/components/EventCard.tsx
flipper/src/components/ListaDeEventos.tsx
flipper/src/components/Menu.tsx
flipper/src/components/NavBar.tsx
flipper/src/pages/home/index.tsx

[comente unos console log y acomode el margin en tamaño md]

96 crear menu de la navbar

---

flipper/src/components/Perfil/PerfilEmpresa.tsx
flipper/src/pages/api/trabajador/[id].ts
flipper/src/pages/postulaciones/[idPostulante].tsx
flipper/src/pages/postulaciones/index.tsx

agregue ruta postulaciones/[idPostulante] donde se va a mostrar los datos del postulante al evento
modifique ruta GET trabajador/id para devolver solo los datos necesarios. 
Falta modificar la ruta trabajador para devolver la edad

Ruta perfil trabajador por id

---

flipper/package-lock.json
flipper/package.json
flipper/src/components/CrearEvento/CreateEventForm.tsx

alertas al crear evento

---

flipper/prisma/schema.prisma
flipper/src/pages/postulaciones/[idPostulante].tsx

se agregó funcionalidad al botón volver 
al descargar solo un alerta, faltaría hacer la descarga de la documentación

perfil postulante con boton volver y descargar

---

flipper/src/components/NavBar.tsx
flipper/src/pages/evento/[idEvent].tsx

estilado componente detalle del evento

Como empresa quiero una pestaña en donde pueda ver los postulados actuales y decidir a quien contratar o rechazar

---

flipper/src/components/Menu/ListaDePestanasDelMenu.tsx
flipper/src/components/Menu/Menu.tsx
flipper/tailwind.config.js

estilos al nav-menu

---

flipper/src/components/HistorialDeEventos/Historial.tsx
flipper/src/components/HistorialDeEventos/HistorialTrabajador.tsx
flipper/src/components/ListaDeEventos/EventosConfirmadosTrabajador.tsx
flipper/src/components/ListaDeEventos/EventosTrabajador.tsx
flipper/src/components/Menu/ListaDePestanasDelMenu.tsx
flipper/src/components/Menu/Menu.tsx
flipper/src/components/NavBar.tsx
flipper/src/components/Perfil/PerfilTrabajador.tsx
flipper/src/context/MenuContext.tsx
flipper/src/pages/home/index.tsx
flipper/src/types/Types.ts
flipper/src/utils/BotonesDePestañasDelMenu.ts

Tuve que crear los componentes 
HistorialTrabajador
EventosConfirmadosTrabajador
EventosTrabajador
PerfilTrabajador
para poder adaptar el Menu, pueden arrojar ahi adentro su codigo

menu para trabajador

---

flipper/package-lock.json
flipper/package.json
flipper/src/components/Menu/Menu.tsx

ahora tiene un telefono de ejemplo

Feature: Boton de ayuda ahora redirige a un contacto de whatsapp,

---

flipper/src/components/ListaDeEventos/EventosTrabajador.tsx
flipper/src/components/ListaDeEventosTrabajador/EventCardTrabajador.tsx
flipper/src/components/ListaDeEventosTrabajador/EventosTrabajador.tsx
flipper/src/components/ListaDeEventosTrabajador/ListaDeEventosTrabajador.tsx
flipper/src/components/Menu/Menu.tsx
flipper/src/pages/api/trabajador/eventos/index.ts
flipper/src/pages/home/index.tsx

Se agrego la lista de eventos por ciudad para el trabajador

lista de eventos trabajador por ciudad

---

flipper/src/components/Login/index.tsx
flipper/src/pages/api/users/gestionDeContrasena/cambiarContrasena.ts
flipper/src/pages/api/users/gestionDeContrasena/recuperarContrasena.ts
flipper/src/pages/gestionDeContrasena/cambiarContrasena/[email].tsx
flipper/src/pages/gestionDeContrasena/recuperarContrasena.tsx
flipper/src/pages/index.tsx
flipper/src/services/cambiarContrasena.ts
flipper/src/services/recuperarContrasena.ts
flipper/src/services/transportEmail.ts
flipper/src/types/Types.ts
flipper/src/utils/validationCambiarContrasenaSchema.ts
flipper/src/utils/validationRecupContrasenaSchema.ts

Movido login de index general a componente Login
Recuperar contraseña 
Mergeo Recuperar contraseña con Notificaciones y conflictos arreglados

76 no olvidarse de hacer un sistema para recuperar la password

---

flipper/src/components/ListaDeEventos/EventosConfirmadosTrabajador.tsx
flipper/src/components/ListaDeEventos/ListaEventosTrabajador.tsx

Falta estilar el componente ListaEventosTrabajador

funcionalidad lista para eventos confirmados

---

flipper/prisma/schema.prisma
flipper/src/components/Perfil/PerfilTrabajador.tsx
flipper/src/pages/api/trabajador/index.ts
flipper/src/pages/api/trabajador/modTrabajador.ts

182 perfil trabajador y edicion de datos

---

flipper/cors.json
flipper/src/components/Perfil/PerfilTrabajador.tsx
flipper/src/pages/api/trabajador/index.ts
flipper/src/pages/postulaciones/[idPostulante].tsx
flipper/src/utils/firebase.ts

Se modifico el perfil trabajador que ve la empresa

refactor de estilos para los postulantes que ve la empresa

---

flipper/src/components/CrearEvento/CreateEventForm.tsx

Se agrego el campo establecimiento, queda pendiente agregarlo a la tabla de eventos y hacer el db push, solo que pide resetear la base de datos

se agrego el campo establecimiento

---

flipper/src/components/ListaDeEventosTrabajador/EventCardTrabajador.tsx
flipper/src/pages/api/trabajadoreseneventos/index.ts

Validación en el back y modal para ir al perfil, en caso de que no pueda postularse por no completar sus datos

Hotfix postulaciones

---

flipper/prisma/schema.prisma
flipper/src/components/CrearEvento/CreateEventForm.tsx
flipper/src/components/Perfil/PerfilTrabajador.tsx
flipper/src/pages/api/event/create-event/index.ts

Fix del formulario, se agrego el campo establecimiento a la db

fix formulario

---

flipper/prisma/schema.prisma
flipper/src/pages/api/admin/empresa/index.ts
flipper/src/pages/api/admin/evento/index.ts
flipper/src/pages/api/admin/index.ts
flipper/src/pages/api/admin/trabajador/index.ts
flipper/src/pages/api/empresa/index.ts
flipper/src/pages/api/event/admitirOrestringirPostulaciones/index.ts
flipper/src/pages/api/event/create-event/index.ts
flipper/src/pages/api/event/index.ts
flipper/src/pages/api/trabajador/modTrabajador.ts
flipper/src/pages/api/trabajadoreseneventos/index.ts

Ahora las rutas del back, evaluan cada una, si se le pasa un token valido, de no ser asi, no se realiza la peticion y tira error de token invalido

se agrego verificacion por token antes de realizar una peticion
